title: 'Let Me Tell You a Story'
default_lang: en
author:
  name: 'Geoff Sowrey'
  email: geoff@sowrey.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Fables, anecdotes, fiction, history, and narratives by Geoff Sowrey'
  title: 'Let Me Tell You a Story'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
